sonar.projectKey=adminx
sonar.organization=rakeshc554-code

sonar.sources=backend/src,frontend/src
sonar.tests=.
sonar.test.inclusion=**/*.test.ts,**/*.test.tsx
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=**/*.config.*,**/node_modules/**,**/*.d.ts

sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,frontend/node_modules/**

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
